### ISSUE TITLE
WebP Images Error Out: WebP Image ID is undefined when uploading

### ISSUE THREAD

**Issue by ronalfy** [DLXPlugins/photo-block#1]
## What is the desired behavior?

When first inserting the block and uploading a WebP image, I should be able to crop it.

## What is the actual behavior?

When uploading a WebP image and trying to crop the image, the crop screen can't load in the image and errors out to console.

<img width="1261" alt="Screenshot 2023-05-06 at 00 20 32" src="https://user-images.githubusercontent.com/636521/236601792-5eec79ea-c23e-408f-82d7-62384dd6a351.png">

## Steps to reproduce undesired behavior:

Detail how to reproduce the bug.

1. Add the block to the block editor
2. Upload a WebP image
3. Try to crop it
4. Observe error in console

## Screenshots or Video

Add screenshots or videos to the issue. These help out immensely with diagnosing unexpected behavior.

https://user-images.githubusercontent.com/636521/236601941-472b8d60-4b58-4067-a5cc-855821af3004.mp4

## Additional Comments

This could be a REST API issue with processing the image and saving the attachment. This seems to only happen with WebP images.

**Comment by ajaydsouza** [comment]
https://user-images.githubusercontent.com/2140870/236619942-3a8571eb-f781-4a8b-9b3a-49c85da1fce6.mp4

I have a different issue. The webp file uploads but the upladign sequence doesn't complete. I have a similar issue in the normal image block, I think. However, it does upload as it shows up in the Media Library.

The first time I select and insert it, I get an error but the second time it works properly. It also works properly when selecting an existing webp.

I don't have an issue when I then hit the crop button.
